<?php
return [

// Heading
    'heading_title'   => 'Image Manager',

// Text
    'text_uploaded'   => 'Success: Your file has been uploaded!',
    'text_directory'  => 'Success: Directory created!',
    'text_delete'     => 'Success: Your file or directory has been deleted!',

// Entry
    'entry_search'    => 'Search..',
    'entry_folder'    => 'Folder Name',

// Error
    'error_permission'=> 'Warning: Permission Denied!',
    'error_filename'  => 'Warning: Filename must be between 3 and 255!',
    'error_folder'    => 'Warning: Folder name must be between 3 and 255!',
    'error_exists'    => 'Warning: A file or directory with the same name already exists!',
    'error_directory' => 'Warning: Directory does not exist!',
    'error_filetype'  => 'Warning: Incorrect file type!',
    'error_upload'    => 'Warning: File could not be uploaded for an unknown reason!',
    'error_delete'    => 'Warning: You can not delete this directory!',

    // Text
    'text_yes'                      => 'Yes',
    'text_no'                       => 'No',
    'text_enabled'                  => 'Enabled',
    'text_disabled'                 => 'Disabled',
    'text_none'                     => ' --- None --- ',
    'text_select'                   => ' --- Please Select --- ',
    'text_select_all'               => 'Select All',
    'text_unselect_all'             => 'Unselect All',
    'text_all_zones'                => 'All Zones',
    'text_default'                  => ' <b>(Default)</b>',
    'text_close'                    => 'Close',
    'text_pagination'               => 'Showing %d to %d of %d (%d Pages)',
    'text_loading'                  => 'Loading...',
    'text_no_results'               => 'No results!',
    'text_confirm'                  => 'Are you sure?',
    'text_home'                     => 'Home',

// Button
    'button_add'                    => 'Add New',
    'button_delete'                 => 'Delete',
    'button_save'                   => 'Save',
    'button_cancel'                 => 'Cancel',
    'button_cancel_recurring'       => 'Cancel Recurring Payments',
    'button_continue'               => 'Continue',
    'button_clear'                  => 'Clear',
    'button_close'                  => 'Close',
    'button_enable'                 => 'Enable',
    'button_disable'                => 'Disable',
    'button_filter'                 => 'Filter',
    'button_send'                   => 'Send',
    'button_edit'                   => 'Edit',
    'button_copy'                   => 'Copy',
    'button_back'                   => 'Back',
    'button_remove'                 => 'Remove',
    'button_refresh'                => 'Refresh',
    'button_export'                 => 'Export',
    'button_import'                 => 'Import',
    'button_download'               => 'Download',
    'button_rebuild'                => 'Rebuild',
    'button_upload'                 => 'Upload',
    'button_submit'                 => 'Submit',
    'button_invoice_print'          => 'Print Invoice',
    'button_shipping_print'         => 'Print Shipping List',
    'button_address_add'            => 'Add Address',
    'button_attribute_add'          => 'Add Attribute',
    'button_banner_add'             => 'Add Banner',
    'button_custom_field_value_add' => 'Add Custom Field',
    'button_product_add'            => 'Add Product',
    'button_filter_add'             => 'Add Filter',
    'button_option_add'             => 'Add Option',
    'button_option_value_add'       => 'Add Option Value',
    'button_recurring_add'          => 'Add Recurring',
    'button_discount_add'           => 'Add Discount',
    'button_special_add'            => 'Add Special',
    'button_image_add'              => 'Add Image',
    'button_geo_zone_add'           => 'Add Geo Zone',
    'button_history_add'            => 'Add History',
    'button_transaction_add'        => 'Add Transaction',
    'button_route_add'              => 'Add Route',
    'button_rule_add'               => 'Add Rule',
    'button_module_add'             => 'Add Module',
    'button_link_add'               => 'Add Link',
    'button_approve'                => 'Approve',
    'button_reset'                  => 'Reset',
    'button_generate'               => 'Generate',
    'button_voucher_add'            => 'Add Voucher',
    'button_reward_add'             => 'Add Reward Points',
    'button_reward_remove'          => 'Remove Reward Points',
    'button_commission_add'         => 'Add Commission',
    'button_commission_remove'      => 'Remove Commission',
    'button_credit_add'             => 'Add Credit',
    'button_credit_remove'          => 'Remove Credit',
    'button_ip_add'                 => 'Add IP',
    'button_parent'                 => 'Parent',
    'button_folder'                 => 'New Folder',
    'button_search'                 => 'Search',
    'button_view'                   => 'View',
    'button_install'                => 'Install',
    'button_uninstall'              => 'Uninstall',
    'button_login'                  => 'Login into Store',
    'button_unlock'                 => 'Unlock Account',
    'button_link'                   => 'Link',
    'button_currency'               => 'Refresh Currency Values',
    'button_apply'                  => 'Apply',
    'button_category_add'           => 'Add Category',
    'button_order'                  => 'View Order',
    'button_order_recurring'        => 'View Recurring Order'

];
